server:
  port: 8088

spring:
  activemq:
    user: admin
    password: admin
    broker-url: tcp://192.168.0.131:61616
    pool:
      enabled: true
      max-connections: 10

queue:
  name: test.queue
topic:
  name: test.topic

