server:
  port: 8088
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#  primary-datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    jdbc-url: jdbc:mysql://192.168.0.101:3306/msdb?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
#    username: root
#    password: root
#  secondary-datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    jdbc-url: jdbc:mysql://192.168.0.101:3306/msdb?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
#    username: root
#    password: root
  custom:
    datasource:
      load-balancer-name: round-robin
      names: primary_ds,secondary_ds_0
      primary_ds:
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.0.101:3306/msdb?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
        username: root
        password: root
        type: com.zaxxer.hikari.HikariDataSource

      secondary_ds_0:
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.137.10:3306/msdb?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
        username: root
        password: root
        type: com.zaxxer.hikari.HikariDataSource