server:
  port: 8087
  servlet:
    context-path: /inventory-service

spring:
  application:
    name: @artifactId@
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.130:3306/liquid_stock?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
  redis:
    host: 192.168.0.130
    password: root
# MyBatis Plus 配置项
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 虽然默认为 true ，但是还是显示去指定下。
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)


